# Generated by Django 3.1.6 on 2021-08-19 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('picture', models.FileField(max_length=255, upload_to='', verbose_name='Изображение')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('parent_picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.image', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'db_table': 'picture',
            },
        ),
    ]
