# Generated by Django 3.1.6 on 2021-08-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_image_image_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_thumb',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Изображение'),
        ),
    ]
