# Generated by Django 3.1.6 on 2021-08-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210825_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_thumb',
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
